/**
 * npm run registry:sync
 *
 * Cross-checks our aircraft registry against Bellingcat's `modes.csv` — tar1090-db plus
 * ownership from hexdb.io, 495k aircraft, MIT licensed.
 *
 * It deliberately does not edit the seed. Third-party fields land in namespaced columns,
 * discrepancies are printed for a person to judge, and Slovak state or military aircraft
 * missing from our registry are listed as candidates. Nothing enters the registry without
 * someone deciding and a source recorded.
 *
 * That last report is the point. This project twice concluded an aircraft did not exist
 * after checking one register — the Air Force Global 5000s and then its Black Hawks. One
 * column of this file would have answered both.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { eq } from 'drizzle-orm'
import { closeDb, getDb } from '../db/client.js'
import { aircraft, source } from '../db/schema.js'
import { flag, parseArgs, runCli } from '../lib/cli.js'
import { log } from '../lib/log.js'

const URL =
  'https://raw.githubusercontent.com/bellingcat/adsb-history/main/backend-data-loading/modes.csv'
const CACHE = './data/cache/modes.csv'
const SOURCE_ID = 'src-bellingcat-modes'

/** The ICAO 24-bit block allocated to Slovakia. */
const SK_PREFIX = '505'
/** Owner strings that mark an aircraft as worth a human's attention. */
const STATE_OWNER = /(slovak air force|government of slovakia|ministry of|air force|police|state)/i

type ModesRow = {
  hex: string
  registration: string
  manufacturer: string
  typecode: string
  type: string
  owner: string
  operator: string
  aircraft: string
  category: string
  military: string
  year: string
}

function parseLine(line: string): string[] {
  const out: string[] = []
  let field = ''
  let quoted = false
  for (let i = 0; i < line.length; i++) {
    const c = line[i]!
    if (quoted) {
      if (c === '"') {
        if (line[i + 1] === '"') { field += '"'; i++ } else quoted = false
      } else field += c
    } else if (c === '"') quoted = true
    else if (c === ',') { out.push(field); field = '' }
    else field += c
  }
  out.push(field)
  return out
}

async function load(force: boolean): Promise<string> {
  const path = resolve(process.cwd(), CACHE)
  if (!force && existsSync(path)) {
    log.info(`using cached ${CACHE}`)
    return readFileSync(path, 'utf8')
  }
  log.info(`downloading ${URL} (about 43 MB)`)
  const response = await fetch(URL)
  if (!response.ok) throw new Error(`modes.csv download failed: HTTP ${response.status}`)
  const text = await response.text()
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, text)
  return text
}

async function main(): Promise<void> {
  const args = parseArgs()
  const text = await load(flag(args, 'force'))
  const lines = text.split('\n')
  const header = parseLine(lines[0] ?? '')
  const index = (name: string): number => header.indexOf(name)

  const byHex = new Map<string, ModesRow>()
  const slovak: ModesRow[] = []

  for (let i = 1; i < lines.length; i++) {
    const line = lines[i]
    if (!line) continue
    const f = parseLine(line)
    const hex = (f[index('hex')] ?? '').toLowerCase()
    if (!hex) continue
    const row: ModesRow = {
      hex,
      registration: f[index('registration')] ?? '',
      manufacturer: f[index('manufacturer')] ?? '',
      typecode: f[index('typecode')] ?? '',
      type: f[index('type')] ?? '',
      owner: f[index('owner')] ?? '',
      operator: f[index('operator')] ?? '',
      aircraft: f[index('aircraft')] ?? '',
      category: f[index('category')] ?? '',
      military: f[index('military')] ?? '',
      year: f[index('year')] ?? '',
    }
    byHex.set(hex, row)
    if (hex.startsWith(SK_PREFIX) && (row.military === 't' || STATE_OWNER.test(row.owner))) {
      slovak.push(row)
    }
  }
  console.log(`modes.csv: ${byHex.size.toLocaleString('en-GB')} aircraft`)

  const { db } = await getDb()
  await db
    .insert(source)
    .values({
      id: SOURCE_ID,
      publisher: 'Bellingcat',
      title: 'adsb-history / modes.csv — augmented aircraft database',
      url: URL,
      type: 'adsb',
      sourceTier: 'C',
      notes:
        'tar1090-db plus ownership from hexdb.io. The category and military columns are ' +
        'generated by a large language model per their README, so those two are tier D.',
    })
    .onConflictDoUpdate({ target: source.id, set: { accessedAt: new Date(), url: URL } })

  const ours = await db.select().from(aircraft)
  const discrepancies: string[] = []
  let enriched = 0

  for (const row of ours) {
    const m = byHex.get(row.icao24)
    if (!m) {
      discrepancies.push(`${row.registration ?? row.icao24}: not present in modes.csv at all`)
      continue
    }
    await db
      .update(aircraft)
      .set({
        registryOwner: m.owner || null,
        registryOperatorCode: m.operator || null,
        registryType: m.type || m.aircraft || null,
        registryYear: m.year || null,
        registryCategory: m.category || null,
        registryMilitary: m.military === 't',
        registrySyncedAt: new Date(),
      })
      .where(eq(aircraft.id, row.id))
    enriched++

    if (m.registration && row.registration && m.registration !== row.registration) {
      discrepancies.push(
        `${row.icao24}: we say ${row.registration}, modes.csv says ${m.registration}`,
      )
    }
    if (m.typecode && row.typeCode && m.typecode !== row.typeCode) {
      discrepancies.push(
        `${row.registration}: type ${row.typeCode} here, ${m.typecode} in modes.csv`,
      )
    }
  }
  console.log(`enriched ${enriched} of ${ours.length} registry entries`)

  if (discrepancies.length) {
    console.log('\nDISCREPANCIES — for a person to judge, nothing changed automatically')
    for (const d of discrepancies) console.log(`  ${d}`)
  } else {
    console.log('\nno discrepancies between our registry and modes.csv')
  }

  const known = new Set(ours.map((r) => r.icao24))
  const missing = slovak.filter((m) => !known.has(m.hex))
  console.log(
    `\nSLOVAK STATE OR MILITARY AIRCRAFT NOT IN OUR REGISTRY — ${missing.length}\n` +
      '  Candidates only. Adding one is a decision, with a source, in the seed file.',
  )
  for (const m of missing.sort((a, b) => a.hex.localeCompare(b.hex))) {
    console.log(
      `  ${m.hex}  ${(m.registration || '—').padEnd(9)} ${(m.typecode || '').padEnd(6)} ` +
        `${(m.owner || 'owner unknown').padEnd(28)} ${m.aircraft}`,
    )
  }

  await closeDb()
}

runCli(main)
